### ISSUE TITLE
IEex loader issue. Error occurs whilst attempting to inject IEex.dll, game won't start

### ISSUE THREAD

**Issue by dgarry7** [RedChimera/IWD2EE#110]
The game used to launch correctly, now when I try to launch it I get two error messages. Please advise. Thanks, David
![IEex loader error1](https://github.com/RedChimera/IWD2EE/assets/146393132/a1885328-23da-4143-8fa1-637ce0289b2d)
![IEex loader error2](https://github.com/RedChimera/IWD2EE/assets/146393132/cabc38ac-0ff0-44e0-b985-e65527b77e1c)

**Comment by Bubb13** [comment]
Try:
1. Running IWD2EE.exe as admin, and
2. Creating an exception in your antivirus software

**Comment by dgarry7** [comment]
1. I do attempt to run IWD2EE.exe as admin.
2. I don't think I have any anti-virus software on this PC. I don't see any in Programs and Features.
Thank you for your quick reply!

**Comment by dgarry7** [comment]
Here's the solution. I found this thread:

"Before you install IWD2:EE, if you installed IWD2 from GOG, please run setup-ddrawfix.exe (found in your game folder) and go through the steps to uninstall it. IWD2:EE comes with a preconfigured cnc-ddraw replacement for ddrawfix, but won't use it if it detects ddrawfix is already installed. Critically, cnc-ddraw allows the game to upscale to your monitor's resolution.

So even though I had already been playing the game before this issue cropped up, I ran setup-ddrawfix.exe, chose (u) to uninstall (it took a long time to complete).

Then I followed these steps found here:

https://github.com/FunkyFr3sh/cnc-ddraw/releases/tag/v6.3.0.0

"Download cnc-ddraw.zip and extract it into your game folder
Start the game"

**Comment by Bubb13** [comment]
That's strange, since cnc-ddraw should have nothing to do with the initial injection of IEex, and newer versions of IWD2EE will replace ddrawfix with cnc-ddraw for you. In any case, glad you got your game working.
