### ISSUE TITLE
Add credits for IEex loader (IWD2EE.exe) and IEex.dll

### ISSUE THREAD

**Issue by mrfearless** [RedChimera/IWD2EE#94]
Can you credit my contribution to correctly reflect that the IEex loader (IWD2EE.exe) and IEex.dll was originally created by myself - mrfearless: https://github.com/mrfearless/IEexLoader

Thank you.

**Comment by OlvynChuru** [comment]
Okay!

**Comment by OlvynChuru** [comment]
Sorry for miscrediting the creation of IEex. I will get that fixed in the next update.

**Comment by Bubb13** [comment]
I should have caught the omission shortly after IWD2:EE was released. Apologies, we'll get it fixed soon.

**Comment by mrfearless** [comment]
Thanks, much appreciated. Also congratulations on the release, I look forward to checking it out. Cheers.
