### ISSUE TITLE
Anti-virus virus warning.

### ISSUE THREAD

**Issue by lixicus** [RedChimera/IWD2EE#96]
Bitdefender says [IWD2EE Version 3.2.1] has Gen:Variant.Jaik.197725
Arcabit says [IWD2EE Version 3.2.1] has Trojan.Jaik.D3045D
DeepInstinct says [IWD2EE Version 3.2.1] MALICIOUS
MAX Malware says [IWD2EE Version 3.2.1] (ai Score=84)
SentinelOne (Static ML) says [IWD2EE Version 3.2.1] Static AI - Suspicious PE

**Comment by OlvynChuru** [comment]
That's a false alarm. The methods that IWD2EE uses to modify IWD2 are incorrectly detected by anti-virus as malicious. But IWD2EE is completely safe to use. I recommend you exclude IWD2EE.exe from your anti-virus.
